# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/CLion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/CLion/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/goddino/repositories/CppAlessiaBot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/goddino/repositories/CppAlessiaBot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/CLion/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/CLion/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/goddino/repositories/CppAlessiaBot/CMakeFiles /home/goddino/repositories/CppAlessiaBot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/goddino/repositories/CppAlessiaBot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CppAlessiaBot

# Build rule for target.
CppAlessiaBot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CppAlessiaBot
.PHONY : CppAlessiaBot

# fast build rule for target.
CppAlessiaBot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/build
.PHONY : CppAlessiaBot/fast

emoji.o: emoji.cpp.o
.PHONY : emoji.o

# target to build an object file
emoji.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/emoji.cpp.o
.PHONY : emoji.cpp.o

emoji.i: emoji.cpp.i
.PHONY : emoji.i

# target to preprocess a source file
emoji.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/emoji.cpp.i
.PHONY : emoji.cpp.i

emoji.s: emoji.cpp.s
.PHONY : emoji.s

# target to generate assembly for a file
emoji.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/emoji.cpp.s
.PHONY : emoji.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/main.cpp.s
.PHONY : main.cpp.s

stringUtils.o: stringUtils.cpp.o
.PHONY : stringUtils.o

# target to build an object file
stringUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/stringUtils.cpp.o
.PHONY : stringUtils.cpp.o

stringUtils.i: stringUtils.cpp.i
.PHONY : stringUtils.i

# target to preprocess a source file
stringUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/stringUtils.cpp.i
.PHONY : stringUtils.cpp.i

stringUtils.s: stringUtils.cpp.s
.PHONY : stringUtils.s

# target to generate assembly for a file
stringUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppAlessiaBot.dir/build.make CMakeFiles/CppAlessiaBot.dir/stringUtils.cpp.s
.PHONY : stringUtils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CppAlessiaBot"
	@echo "... emoji.o"
	@echo "... emoji.i"
	@echo "... emoji.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stringUtils.o"
	@echo "... stringUtils.i"
	@echo "... stringUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

